// MODAL
export const LOGIN_MODAL_TOGGLE = "LOGIN_MODAL_TOGGLE";
export const REGISTER_MODAL_TOGGLE = "REGISTER_MODAL_TOGGLE";
export const SALT_MODAL_TOGGLE = "SALT_MODAL_TOGGLE";
export const POST_MODAL_TOGGLE = "POST_MODAL_TOGGLE";
export const QUESTION_MODAL_TOGGLE = "QUESTION_MODAL_TOGGLE";
export const SET_MODAL_DATA = "SET_MODAL_DATA";

// AUTH
export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const ADD_JOINED_SALT = "ADD_JOINED_SALT";
export const EDIT_JOINED_SALT = "EDIT_JOINED_SALT";
export const REMOVE_JOINED_SALT = "REMOVE_JOINED_SALT";

// SALT
export const GET_SALTS_BEGIN = "GET_SALTS_BEGIN";
export const GET_SALTS_SUCCESS = "GET_SALTS_SUCCESS";
export const GET_SALTS_FAIL = "GET_SALTS_FAIL";

export const GET_SALT_BEGIN = "GET_SALT_BEGIN";
export const GET_SALT_SUCCESS = "GET_SALT_SUCCESS";
export const GET_SALT_FAIL = "GET_SALT_FAIL";

export const CREATE_SALT_BEGIN = "CREATE_SALT_BEGIN";
export const CREATE_SALT_SUCCESS = "CREATE_SALT_SUCCESS";
export const CREATE_SALT_FAIL = "CREATE_SALT_FAIL";

export const EDIT_SALT_BEGIN = "EDIT_SALT_BEGIN";
export const EDIT_SALT_SUCCESS = "EDIT_SALT_SUCCESS";
export const EDIT_SALT_FAIL = "EDIT_SALT_FAIL";

export const DELETE_SALT_BEGIN = "DELETE_SALT_BEGIN";
export const DELETE_SALT_SUCCESS = "DELETE_SALT_SUCCESS";
export const DELETE_SALT_FAIL = "DELETE_SALT_FAIL";

export const JOIN_SALT_BEGIN = "JOIN_SALT_BEGIN";
export const JOIN_SALT_SUCCESS = "JOIN_SALT_SUCCESS";
export const JOIN_SALT_FAIL = "JOIN_SALT_FAIL";

export const LEAVE_SALT_BEGIN = "LEAVE_SALT_BEGIN";
export const LEAVE_SALT_SUCCESS = "LEAVE_SALT_SUCCESS";
export const LEAVE_SALT_FAIL = "LEAVE_SALT_FAIL";

// POST
export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
