// MODAL
export const LOGIN_MODAL_TOGGLE = "LOGIN_MODAL_TOGGLE";
export const REGISTER_MODAL_TOGGLE = "REGISTER_MODAL_TOGGLE";
export const SALT_MODAL_TOGGLE = "SALT_MODAL_TOGGLE";

// AUTH
export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

// SALT
export const GET_SALTS_BEGIN = "GET_SALTS_BEGIN";
export const GET_SALTS_SUCCESS = "GET_SALTS_SUCCESS";
export const GET_SALTS_FAIL = "GET_SALTS_FAIL";

export const CREATE_SALT_BEGIN = "CREATE_SALT_BEGIN";
export const CREATE_SALT_SUCCESS = "CREATE_SALT_SUCCESS";
export const CREATE_SALT_FAIL = "CREATE_SALT_FAIL";
